"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$directory\
(with \
$c\
$dotnet\
$golang\
$nodejs\
$python\
$ruby\
$rust)\
$line_break$character
"""

right_format = """
$git_status\
$git_branch\
$git_commit\
"""

palette = "catppuccin_mocha"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[c]
format = '[$name $version ](fg:green)'
symbol = "  "

[dotnet]
symbol = '  '
format = '[$symbol($version )]($style)'

[character]
success_symbol = "[➜](fg:lavender)"
error_symbol   = "[➜](fg:red)"

[directory]
format = '[at]()[ $path ](fg:blue)'
truncation_length = 3
truncation_symbol = "../"

[git_branch]
format = '[ $symbol $branch:](fg:lavender bg:base)'
symbol = ""

[git_commit]
format = '[$hash](fg:lavender bg:base)'
only_detached = false

[git_metrics]
disabled = false
format = '([](bg:green fg:lavender)[ +$added ](fg:base bg:green))([ -$deleted](fg:base bg:red))'

[git_status]
format = '([$ahead_behind $all_status]($style))'
ahead = '[](fg:white bg:base)'
conflicted = '[](fg:white bg:base)'
behind = '[](fg:white bg:base)'
diverged = '[](fg:red bg:base)'
up_to_date = '[](fg:green bg:base)'
untracked = '[ $count](fg:blue bg:base)[un](fg:blue bg:base)'
stashed = '[ $count](fg:maroon bg:base)[sts](fg:maroon bg:base)'
modified = '[ $count](fg:yellow bg:base)[m](fg:yellow bg:base)'
staged = '[ $count](fg:green bg:base)[stg](fg:green bg:base)'
renamed = '[ $count](fg:mauve bg:base)[rn](fg:mauve bg:base)'
deleted = '[ $count](fg:red bg:base)[d](fg:red bg:base)'

[golang]
format = '[$symbol($version )]($style)'
symbol = "  "

[nodejs]
format = '[$symbol($version )]($style)'
symbol = "  "

[python]
format = '[$symbol($version )](fg:yellow)'
symbol = "  "

[ruby]
format = '[$symbol($version )](fg:red)'
symbol = "  "

[rust]
format = '[$symbol($version )](fg:maroon)'
symbol = "  "

[username]
show_always = true
format = '[$user ](bold fg:yellow)'
