-- icons for literally everything

return {
   'nvim-tree/nvim-web-devicons',
   dependencies = {
      'catppuccin/nvim',
   },
   config = function()
      local icons = require('nvim-web-devicons')
      local palette = require('catppuccin.palettes').get_palette('mocha')

      icons.setup({
         strict = true,
         override_by_extension = {
            bak = { icon = ' ', name = 'Bak' },
            bin = { icon = ' ', name = 'Bin' },
            c = { color = palette.sapphire, icon = ' ', name = 'C' },
            cc = { color = palette.sapphire, icon = ' ', name = 'Cc' },
            cgi = { color = palette.sapphire, icon = ' ', name = 'Cgi' },
            cjs = { color = palette.yellow, icon = ' ', name = 'Cjs' },
            cpp = { color = palette.sapphire, icon = ' ', name = 'Cpp' },
            conf = { icon = ' ', name = 'Conf' },
            cs = { color = palette.lavender, icon = ' ', name = 'Cs' },
            csproj = { color = palette.lavender, icon = ' ', name = 'Csproj' },
            css = { color = palette.blue, icon = ' ', name = 'Css' },
            env = { icon = ' ', name = 'Env' },
            erb = { color = palette.red, icon = ' ', name = 'Erb' },
            gif = { icon = ' ', name = 'Gif' },
            go = { color = palette.teal, icon = ' ', name = 'Go' },
            fish = { icon = ' ', name = 'Fish' },
            html = { color = palette.peach, icon = ' ', name = 'Html' },
            java = { color = palette.maroon, icon = ' ', name = 'Java' },
            jar = { color = palette.maroon, icon = ' ', name = 'Jar' },
            jpg = { icon = ' ', name = 'Jpg' },
            json = { color = palette.green, icon = ' ', name = 'Json' },
            js = { color = palette.yellow, icon = ' ', name = 'Js' },
            mjs = { color = palette.yellow, icon = ' ', name = 'Mjs' },
            jsx = { color = palette.sky, icon = ' ', name = 'Jsx' },
            lock = { icon = ' ', name = 'Lock' },
            kt = { color = palette.mauve, icon = ' ', name = 'Kt' },
            lua = { color = palette.blue, icon = ' ', name = 'Lua' },
            md = { icon = ' ', name = 'Md' },
            ml = { color = palette.peach, icon = ' ', name = 'Ml' },
            mp4 = { icon = ' ', name = 'Mp4' },
            otf = { icon = ' ', name = 'Otf' },
            pdf = { icon = ' ', name = 'Pdf' },
            php = { color = palette.mauve, icon = ' ', name = 'Php' },
            png = { icon = ' ', name = 'Png' },
            ps1 = { icon = ' ', name = 'Ps1' },
            py = { color = palette.yellow, icon = ' ', name = 'Py' },
            so = { icon = ' ', name = 'So' },
            tf = { color = palette.mauve, icon = ' ', name = 'Tf' },
            tfvars = { color = palette.mauve, icon = ' ', name = 'Tfvars' },
            ts = { color = palette.blue, icon = ' ', name = 'Ts' },
            ttf = { icon = ' ', name = 'Ttf' },
            ru = { icon = ' ', name = 'Ru' },
            rb = { color = palette.red, icon = ' ', name = 'Rb' },
            rs = { icon = ' ', name = 'Rs' },
            sass = { color = palette.pink, icon = ' ', name = 'Sass' },
            scss = { color = palette.pink, icon = ' ', name = 'Scss' },
            sh = { icon = ' ', name = 'Sh' },
            sln = { color = palette.lavender, icon = ' ', name = 'Sln' },
            swift = { color = palette.peach, icon = ' ', name = 'Swift' },
            sql = { color = palette.sky, icon = ' ', name = 'Sql' },
            svelte = { color = palette.peach, icon = ' ', name = 'Svelte' },
            svg = { icon = ' ', name = 'Svg' },
            tiff = { icon = ' ', name = 'Tiff' },
            toml = { icon = ' ', name = 'Toml' },
            tsx = { color = palette.sky, icon = ' ', name = 'Tsx' },
            txt = { icon = ' ', name = 'Txt' },
            woff = { icon = ' ', name = 'Woff' },
            xml = { icon = ' ', name = 'Xml' },
            xls = { icon = ' ', name = 'Xls' },
            xz = { icon = ' ', name = 'Xz' },
            yaml = { icon = ' ', name = 'Yaml' },
            yml = { icon = ' ', name = 'Yml' },
            zig = { color = palette.yellow, icon = ' ', name = 'Zig' },
            zip = { icon = ' ', name = 'Zip' },
            zsh = { icon = ' ', name = 'Zsh' },
            ['d.ts'] = { color = palette.blue, icon = ' ', name = 'DTS' },
            ['js.map'] = { color = palette.yellow, icon = ' ', name = 'Jsmap' },
            ['test.js'] = { color = palette.sky, icon = ' ', name = 'TestJs' },
            ['test.jsx'] = { color = palette.sky, icon = ' ', name = 'TestJsx' },
            ['test.ts'] = { color = palette.blue, icon = ' ', name = 'TestTs' },
            ['test.tsx'] = { color = palette.sky, icon = ' ', name = 'TestTsx' },
            ['spec.ts'] = { color = palette.blue, icon = ' ', name = 'Spec' },
         },

         override_by_filename = {
            ['.aliases'] = { icon = ' ', name = 'Aliases' },
            ['.bashrc'] = { icon = ' ', name = 'Bashrc' },
            ['.dockerignore'] = { color = palette.blue, icon = ' ', name = 'Dockerignore' },
            ['.editorconfig'] = { icon = ' ', name = 'Editorconfig' },
            ['.env'] = { icon = ' ', name = 'Env' },
            ['.eslintrc'] = { color = palette.lavender, icon = ' ', name = 'Eslintrc' },
            ['.gitconfig'] = { color = palette.red, icon = ' ', name = 'Gitconfig' },
            ['.gitignore'] = { color = palette.red, icon = ' ', name = 'Gitignore' },
            ['.gitignore_global'] = { color = palette.red, icon = ' ', name = 'Gitignore_global' },
            ['.npmignore'] = { color = palette.red, icon = ' ', name = 'Npmignore' },
            ['.npmrc'] = { color = palette.red, icon = ' ', name = 'Npmrc' },
            ['.nvmrc'] = { color = palette.red, icon = ' ', name = 'Nvmrc' },
            ['.prettierignore'] = { icon = ' ', name = 'Prettierignore' },
            ['.prettierrc'] = { icon = ' ', name = 'Prettierrc' },
            ['.prettierrc.mjs'] = { color = palette.yellow, icon = ' ', name = 'Prettierrc' },
            ['.zshenv'] = { icon = ' ', name = 'Zshenv' },
            ['.zshrc'] = { icon = ' ', name = 'Zshrc' },

            ['alpha'] = { icon = ' ', name = 'Alpha' },
            ['commit_editmsg'] = { color = palette.red, icon = ' ', name = 'Commit' },
            ['config'] = { icon = ' ', name = 'Config' },
            ['config.ru'] = { color = palette.red, icon = ' ', name = 'Config.ru' },
            ['docker-compose.yml'] = { color = palette.blue, icon = ' ', name = 'DockerCompose' },
            ['dockerfile'] = { color = palette.blue, icon = ' ', name = 'Dockerfile' },
            ['eslint.config.js'] = { color = palette.lavender, icon = ' ', name = 'Eslint' },
            ['favicon.ico'] = { color = palette.yellow, icon = ' ', name = 'Favicon' },
            ['go.mod'] = { color = palette.teal, icon = ' ', name = 'Go' },
            ['go.sum'] = { color = palette.teal, icon = ' ', name = 'Go' },
            ['LICENSE.md'] = { icon = ' ', name = 'License' },
            ['license'] = { icon = ' ', name = 'License' },
            ['log'] = { icon = ' ', name = 'Log' },
            ['makefile'] = { icon = ' ', name = 'Makefile' },
            ['package-lock.json'] = { color = palette.red, icon = ' ', name = 'PackageLock' },
            ['pnpm-lock.yaml'] = { color = palette.white, icon = ' ', name = 'DevIconPNPMLock' },
            ['package.json'] = { color = palette.red, icon = ' ', name = 'Package' },
            ['procfile'] = { icon = ' ', name = 'Procfile' },
            ['rake'] = { color = palette.red, icon = ' ', name = 'Rake' },
            ['rakefile'] = { color = palette.red, icon = ' ', name = 'Rakefile' },
            ['README.md'] = { icon = ' ', name = 'Readme' },
            ['svelte.config.js'] = { color = palette.peach, icon = ' ', name = 'Svelte' },
            ['tailwind.config.ts'] = { color = palette.blue, icon = ' ', name = 'Tailwind' },
            ['tsconfig.json'] = { color = palette.blue, icon = ' ', name = 'TsConfig' },
            ['vite.config.ts'] = { color = palette.blue, icon = ' ', name = 'DevIconViteConfig' },
         },
      })

      icons.set_default_icon(' ', palette.text)
   end,
}
