[tools]
bun = "latest"
clojure = "latest"
cmake = "latest"
crush = "latest"
docker-cli = "latest"
docker-compose = "latest"
dotnet = "latest"
erlang = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
go = "latest"
gum = "latest"
herdr = "latest"
java = "latest"
jq = "latest"
kubectl = "latest"
lazydocker = "latest"
lazygit = "latest"
lazyssh = "latest"
mysql = "latest"
neovim = "latest"
node = "lts"
opencode = "latest"
python = "latest"
ripgrep = "latest"
ruby = "latest"
rust = "latest"
starship = "latest"
terraform = "latest"
tmux = "latest"
tree-sitter = "latest"
yazi = "latest"
zellij = "latest"
zig = "latest"
zoxide = "latest"
ollama = "latest"
claude = "latest"

[settings.ruby]
compile = false
