[tools]
bun = "latest"
cmake = "latest"
docker-cli = "latest"
docker-compose = "latest"
dotnet = "latest"
fd = "latest"
fzf = "latest"
go = "latest"
gum = "latest"
java = "latest"
kubectl = "latest"
lazydocker = "latest"
lazygit = "latest"
lazyssh = "latest"
mysql = "latest"
neovim = "latest"
node = "lts"
opencode = "latest"
python = "latest"
ripgrep = "latest"
ruby = "latest"
rust = "latest"
rust-analyzer = "latest"
starship = "latest"
terraform = "latest"
tmux = "latest"
tree-sitter = "latest"
zig = "latest"
zoxide = "latest"
