[tools]
bun = "latest"
fd = "latest"
fzf = "latest"
go = "latest"
neovim = "latest"
node = "lts"
python = "latest"
ripgrep = "latest"
ruby = "latest"
rust = "latest"
starship = "latest"
tmux = "latest"
zig = "latest"
