#!/bin/zsh

if [[ ! -n $(dpkg --get-selections | grep -w $1) ]]; then
    information-message "installing ${1}"

    sudo apt-get install $1 -y

    # do anything you want after install
    $2
else
    success-message "${1} installed"
fi
