#!/bin/zsh

apt_get_install_if_package_not_exists docker-ce
apt_get_install_if_package_not_exists docker-ce-cli
apt_get_install_if_package_not_exists containerd.io
apt_get_install_if_package_not_exists docker-compose-plugin
