#!/usr/bin/env fish

function persist-user-value
    # usage: persist-user-value <name> <value> — appends a global to user.fish
    # (git-ignored). Callers guard with has-user-value, so this only ever appends.
    if test (count $argv) -lt 2
        error-message "persist-user-value: requires a name and value"

        return 1
    end

    set -l file $DOTFILES_DIRECTORY/user.fish

    if not test -f $file
        printf '# generated by configure-user — not tracked in git\n' >$file
    end

    printf 'set -gx %s "%s"\n' $argv[1] "$argv[2]" >>$file
end
