#!/bin/zsh

if brew list $1 &>/dev/null; then
	success_message "${1} is already installed"
else
	information_message "installing ${1}"

	/home/linuxbrew/.linuxbrew/bin/brew install $1

	# do anything you want after install
	$2
fi
