#!/bin/zsh

function rprompt_info() {
	if [[ -d "./.git" ]]; then
		GIT_FILES_TRACKING=''
		MODIFIED_FILES=$(git_modified_files_count)
		STAGED_FILES=$(git_staged_files_count)
		UNTRACKED_FILES=$(git_untracked_files_count)

		if [[ $MODIFIED_FILES > 0 ]]; then
			GIT_FILES_TRACKING+="%K{2}%F{15} ${MODIFIED_FILES}m %f%k"
		fi

		if [[ $STAGED_FILES > 0 ]]; then
			GIT_FILES_TRACKING+="%K{4}%F{15} ${STAGED_FILES}s %f%k"
		fi

		if [[ $UNTRACKED_FILES > 0 ]]; then
			GIT_FILES_TRACKING+="%K{1}%F{15} ${UNTRACKED_FILES}un %f%k"
		fi

		GIT_INFO="%K{8} $(git_branch_name):$(git_sha) %k"

		if [[ -n $GIT_FILES_TRACKING ]]; then
			echo "$GIT_FILES_TRACKING$GIT_INFO"
		else
			echo "$GIT_INFO"
		fi
	fi
}
