-- icons for everything

return {
   'nvim-tree/nvim-web-devicons',
   config = function()
      local icons = require('nvim-web-devicons')

      icons.setup({
         strict = true,
         override_by_extension = vim.tbl_extend('force',
            require('sethen.plugins.nvim-web-devicons-types.extensions.so'),
            require('sethen.plugins.nvim-web-devicons-types.extensions.bin'),
            require('sethen.plugins.nvim-web-devicons-types.extensions.exe'),
            require('sethen.plugins.nvim-web-devicons-types.extensions.dll'),
            require('sethen.plugins.nvim-web-devicons-types.extensions.c'),
            require('sethen.plugins.nvim-web-devicons-types.extensions.csharp'),
            require('sethen.plugins.nvim-web-devicons-types.extensions.css'),
            require('sethen.plugins.nvim-web-devicons-types.extensions.dart'),
            require('sethen.plugins.nvim-web-devicons-types.extensions.docker'),
            require('sethen.plugins.nvim-web-devicons-types.extensions.elixir'),
            require('sethen.plugins.nvim-web-devicons-types.extensions.elm'),
            require('sethen.plugins.nvim-web-devicons-types.extensions.otf'),
            require('sethen.plugins.nvim-web-devicons-types.extensions.ttf'),
            require('sethen.plugins.nvim-web-devicons-types.extensions.woff'),
            require('sethen.plugins.nvim-web-devicons-types.extensions.woff2'),
            require('sethen.plugins.nvim-web-devicons-types.extensions.go'),
            require('sethen.plugins.nvim-web-devicons-types.extensions.graphql'),
            require('sethen.plugins.nvim-web-devicons-types.extensions.gql'),
            require('sethen.plugins.nvim-web-devicons-types.extensions.html'),
            require('sethen.plugins.nvim-web-devicons-types.extensions.png'),
            require('sethen.plugins.nvim-web-devicons-types.extensions.jpg'),
            require('sethen.plugins.nvim-web-devicons-types.extensions.jpeg'),
            require('sethen.plugins.nvim-web-devicons-types.extensions.gif'),
            require('sethen.plugins.nvim-web-devicons-types.extensions.svg'),
            require('sethen.plugins.nvim-web-devicons-types.extensions.webp'),
            require('sethen.plugins.nvim-web-devicons-types.extensions.ico'),
            require('sethen.plugins.nvim-web-devicons-types.extensions.tiff'),
            require('sethen.plugins.nvim-web-devicons-types.extensions.bmp'),
            require('sethen.plugins.nvim-web-devicons-types.extensions.java'),
            require('sethen.plugins.nvim-web-devicons-types.extensions.javascript'),
            require('sethen.plugins.nvim-web-devicons-types.extensions.json'),
            require('sethen.plugins.nvim-web-devicons-types.extensions.jsonc'),
            require('sethen.plugins.nvim-web-devicons-types.extensions.kotlin'),
            require('sethen.plugins.nvim-web-devicons-types.extensions.lua'),
            require('sethen.plugins.nvim-web-devicons-types.extensions.log'),
            require('sethen.plugins.nvim-web-devicons-types.extensions.markdown'),
            require('sethen.plugins.nvim-web-devicons-types.extensions.nginx'),
            require('sethen.plugins.nvim-web-devicons-types.extensions.ocaml'),
            require('sethen.plugins.nvim-web-devicons-types.extensions.perl'),
            require('sethen.plugins.nvim-web-devicons-types.extensions.php'),
            require('sethen.plugins.nvim-web-devicons-types.extensions.python'),
            require('sethen.plugins.nvim-web-devicons-types.extensions.r'),
            require('sethen.plugins.nvim-web-devicons-types.extensions.ruby'),
            require('sethen.plugins.nvim-web-devicons-types.extensions.rust'),
            require('sethen.plugins.nvim-web-devicons-types.extensions.shell'),
            require('sethen.plugins.nvim-web-devicons-types.extensions.sh'),
            require('sethen.plugins.nvim-web-devicons-types.extensions.bash'),
            require('sethen.plugins.nvim-web-devicons-types.extensions.zsh'),
            require('sethen.plugins.nvim-web-devicons-types.extensions.fish'),
            require('sethen.plugins.nvim-web-devicons-types.extensions.svelte'),
            require('sethen.plugins.nvim-web-devicons-types.extensions.sql'),
            require('sethen.plugins.nvim-web-devicons-types.extensions.swift'),
            require('sethen.plugins.nvim-web-devicons-types.extensions.text'),
            require('sethen.plugins.nvim-web-devicons-types.extensions.terraform'),
            require('sethen.plugins.nvim-web-devicons-types.extensions.tfvars'),
            require('sethen.plugins.nvim-web-devicons-types.extensions.toml'),
            require('sethen.plugins.nvim-web-devicons-types.extensions.typescript'),
            require('sethen.plugins.nvim-web-devicons-types.extensions.mp4'),
            require('sethen.plugins.nvim-web-devicons-types.extensions.mkv'),
            require('sethen.plugins.nvim-web-devicons-types.extensions.avi'),
            require('sethen.plugins.nvim-web-devicons-types.extensions.mov'),
            require('sethen.plugins.nvim-web-devicons-types.extensions.webm'),
            require('sethen.plugins.nvim-web-devicons-types.extensions.flv'),
            require('sethen.plugins.nvim-web-devicons-types.extensions.wmv'),
            require('sethen.plugins.nvim-web-devicons-types.extensions.vim'),
            require('sethen.plugins.nvim-web-devicons-types.extensions.vue'),
            require('sethen.plugins.nvim-web-devicons-types.extensions.xml'),
            require('sethen.plugins.nvim-web-devicons-types.extensions.yaml'),
            require('sethen.plugins.nvim-web-devicons-types.extensions.yml'),
            require('sethen.plugins.nvim-web-devicons-types.extensions.zig'),
            require('sethen.plugins.nvim-web-devicons-types.extensions.zip'),
            require('sethen.plugins.nvim-web-devicons-types.extensions.tar'),
            require('sethen.plugins.nvim-web-devicons-types.extensions.gz'),
            require('sethen.plugins.nvim-web-devicons-types.extensions.rar'),
            require('sethen.plugins.nvim-web-devicons-types.extensions.7z'),
            require('sethen.plugins.nvim-web-devicons-types.extensions.xz')
         ),
         override_by_filename = vim.tbl_extend('force',
            require('sethen.plugins.nvim-web-devicons-types.filenames.angular'),
            require('sethen.plugins.nvim-web-devicons-types.filenames.babel'),
            require('sethen.plugins.nvim-web-devicons-types.filenames.biome'),
            require('sethen.plugins.nvim-web-devicons-types.filenames.capacitor'),
            require('sethen.plugins.nvim-web-devicons-types.filenames.docker'),
            require('sethen.plugins.nvim-web-devicons-types.filenames.eslint'),
            require('sethen.plugins.nvim-web-devicons-types.filenames.git'),
            require('sethen.plugins.nvim-web-devicons-types.filenames.go'),
            require('sethen.plugins.nvim-web-devicons-types.filenames.image'),
            require('sethen.plugins.nvim-web-devicons-types.filenames.javascript'),
            require('sethen.plugins.nvim-web-devicons-types.filenames.json'),
            require('sethen.plugins.nvim-web-devicons-types.filenames.kubernetes'),
            require('sethen.plugins.nvim-web-devicons-types.filenames.markdown'),
            require('sethen.plugins.nvim-web-devicons-types.filenames.next'),
            require('sethen.plugins.nvim-web-devicons-types.filenames.npm'),
            require('sethen.plugins.nvim-web-devicons-types.filenames.prettier'),
            require('sethen.plugins.nvim-web-devicons-types.filenames.svelte'),
            require('sethen.plugins.nvim-web-devicons-types.filenames.text'),
            require('sethen.plugins.nvim-web-devicons-types.filenames.tmux'),
            require('sethen.plugins.nvim-web-devicons-types.filenames.typescript'),
            require('sethen.plugins.nvim-web-devicons-types.filenames.xml')
         ),
      })

      icons.set_default_icon(' ')
   end,
}