#!/bin/zsh

function rprompt-info() {
    if [[ -d "./.git" ]]; then
	GIT_FILES_TRACKING=''
	MODIFIED_FILES=$(git-modified-files-count)
	STAGED_FILES=$(git-staged-files-count)
	UNTRACKED_FILES=$(git-untracked-files-count)

	if [[ $MODIFIED_FILES > 0 ]]; then
	    GIT_FILES_TRACKING+="%F{2} ${MODIFIED_FILES}m%f"
	fi

	if [[ $STAGED_FILES > 0 ]]; then
	    GIT_FILES_TRACKING+="%F{3} ${STAGED_FILES}s%f"
	fi

	if [[ $UNTRACKED_FILES > 0 ]]; then
	    GIT_FILES_TRACKING+="%F{1} ${UNTRACKED_FILES}u%f"
	fi

	GIT_INFO=" $(git-branch-name)"

	if [[ -n $GIT_FILES_TRACKING ]]; then
	    echo "%K{#1E1E2E}%F{#313244}%f%k%K{#313244} $GIT_INFO$GIT_FILES_TRACKING %k"
	else
	    echo "%K{#1E1E2E}%F{#313244}%f%k%K{#313244} $GIT_INFO %k"
	fi
    fi
}
