set -g @tpm_plugins '~/.config/tmux/plugins/'

set-option -g renumber-windows on
set -g base-index 1
setw -g pane-base-index 1

set -g @tmux-dotbar-bg "#1e1e2e"
set -g @tmux-dotbar-fg-current "#f9e2af"
set -g @tmux-dotbar-fg "#6c7086"
set -g @tmux-dotbar-fg-prefix "#a6e3a1"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'vaaleyard/tmux-dotbar'

bind-key "K" display-popup -E -w 40% "sesh connect \"$(
  sesh list -i | gum filter --limit 1 --placeholder 'Pick a sesh'
)\""

run '~/.config/tmux/plugins/tpm/tpm'
