set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'vaaleyard/tmux-dotbar'

bind-key "K" display-popup -E -w 40% "sesh connect \"$(
  sesh list -i | gum filter --limit 1 --placeholder 'Pick a sesh'
)\""

set -g @tmux-dotbar-bg "#1e1e2e"
set -g @tmux-dotbar-status-left " #S" # see code
run '~/.tmux/plugins/tpm/tpm'
